CREATE TABLE pets2 (name VARCHAR(50));
ALTER TABLE pets2 ADD COLUMN species VARCHAR(50);
ALTER TABLE pets2 ADD COLUMN breed VARCHAR(50);
ALTER TABLE pets2 ADD COLUMN user VARCHAR(50);
ALTER TABLE pets2 ADD COLUMN notes TEXT(200);
INSERT INTO pets2 (name, species, breed, user) VALUES ("Aggie", "canine", "bearded collie", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("AJ", "canine", "Shetland sheepdog", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Angel", "canine", "Chihuahua", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("April", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Archie", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Aggie", "canine", "bearded collie", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Asheville", "feline", "random-bred", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Asparagus", "feline", "random-bred", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Asta", "canine", "wire fox terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Astro", "canine", "cartoon", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Auggie", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Babe", "pig", "unknown", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Beacon", "canine", "greyhound", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Beamer", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Bella", "canine", "pug", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Bixby", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Blackie", "canine", "random-bred", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Bob", "canine", "random-bred", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Brooklyn", "canine", "Airedale terrier", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Brutus", "canine", "greyhound", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Bully", "feline", "Siamese", "TB");
INSERT INTO pets2 (name, species, breed, user) VALUES ("Bunter", "feline", "random-bred", "TB");
