INSERT INTO petsA (id, name) 
VALUES
	(1, "Abigail"),
    (2, "Abram"),
    (3, "Ace"),
    (4, "Addie"),
    (5, "Agatha"),
    (6, "Aggie"),
    (7, "Aila"),
    (8, "AJ"),
    (9, "Ajax"),
    (10, "Alana"),
    (11, "Alex"),
    (12, "Alexandria"),
    (13, "Ali"),
    (14, "Alice"),
    (15, "Allen"),
    (16, "Alley"),
    (17, "Allora"),
    (18, "Ally"),
    (19, "Amanda"),
    (20, "Amber"),
    (21, "Amos"),
    (22, "Ana"),
    (23, "Anakin"),
    (24, "Andy"),
    (25, "Angel"),
    (26, "Angel Rose"),
    (26, "Angus"),
    (27, "Annie"),
    (28, "April"),
    (29, "Archie"),
    (30, "Arco"),
    (31, "Ariel"),
    (32, "Arliss"),
    (33, "Arlo"),
    (34, "Art"),
    (35, "Asheville"),
    (36, "Ashley"),
    (37, "Asparagus"),
    (38, "Aspen"),
    (39, "Asta"),
    (40, "Asti"),
    (41, "Astro"),
    (42, "Audio"),
    (43, "Auggie"),
    (44, "Auki"),
    (45, "Austin"),
    (46, "Autumn");
SELECT * FROM petsA;    
    
    
